#! /usr/bin/env lua

-- Copyright (C) 2015 Tomoyuki Fujimori <moyu@dromozoa.com>
--
-- This file is part of dromozoa-image.
--
-- dromozoa-image is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- dromozoa-image is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with dromozoa-image.  If not, see <http://www.gnu.org/licenses/>.

local w, h, a, b, c, d = ...

w = tonumber(w)
h = tonumber(h)
a = tonumber(a)
b = tonumber(b)
c = tonumber(c)
d = tonumber(d)

local depth
local tupltype
local data

if d then
  depth = 4
  tupltype = "RGB_ALPHA"
  data = string.char(a, b, c, d)
elseif c then
  depth = 3
  tupltype = "RGB"
  data = string.char(a, b, c)
elseif b then
  depth = 2
  tupltype = "GRAYSCALE_ALPHA"
  data = string.char(a, b)
else
  depth = 1
  tupltype = "GRAYSCALE"
  data = string.char(a)
end

io.write(([[
P7
WIDTH %d
HEIGHT %d
DEPTH %d
MAXVAL 255
TUPLTYPE %s
ENDHDR
]]):format(w, h, depth, tupltype))

for i = 1, w * h do
  io.write(data)
end
