#! /bin/sh -e

# Copyright (C) 2015 Tomoyuki Fujimori <moyu@dromozoa.com>
#
# This file is part of dromozoa-image.
#
# dromozoa-image is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dromozoa-image is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dromozoa-image.  If not, see <http://www.gnu.org/licenses/>.

for i in 1 2 3 4
do
  for j in "f$i" "g$i"
  do
    convert "$j.pam" "magick-$j.png"
    convert "$j.pam" "magick-$j.tga"
  done
done

for i in 1 3
do
  case x$i in
    x1) pnm=pgm;;
    x3) pnm=ppm;;
  esac
  for j in "f$i" "g$i"
  do
    convert "$j.pam" "magick-$j.$pnm"
    convert "$j.pam" -compress none "magick-$j-plain.$pnm"
  done
done
